[versions]

compose = "1.8.3"
compose-compiler = "1.5.14"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
agp = "8.12.0"
accompanist = "0.37.3"
room = "2.7.2"
androidx-credentials = "1.5.0"
google-identity-googleid = "1.1.1"

jetbrains-kotlinx-serialization = "1.9.0"
jetbrains-kotlinx-collections-immutable = "0.4.0"
jetbrains-kotlinx-coroutines = "1.10.2"
jetbrains-kotlinx-datetime = "0.7.1"

androidx-core = "1.16.0"
androidx-collection = "1.5.0"
androidx-appcompat = "1.7.1"
androidx-activity = "1.10.1"
androidx-compose-material3 = "1.3.2"
androidx-constraintlayout-compose = "1.1.1"
androidx-profileinstaller = "1.4.1"
androidx-datastore = "1.1.7"
androidx-navigation-safeargs = "2.9.3"
androidx-test-junit = "1.3.0"
androidx-lifecycle = "2.9.2"

hilt = "2.57"
hilt-navigation-compose = "1.2.0"

zstd-jni = "1.5.7-4"
solarized = "1.0.8"
hlcaptain-compose-scrollbar = "0.0.3-alpha"
saket-swipe = "1.3.0"
timber = "5.0.1"
compose-destinations = "2.2.0"
coil-compose = "2.7.0"
apache-commons-math3 = "3.6.1"

mapbox-maps = "11.14.0"
mapbox-search = "2.14.0"
mapbox-navigation = "3.11.0"

google-secrets = "2.0.1"
google-gms-services = "4.4.3"
google-gms-play-services-location = "21.3.0"
google-gms-play-services-auth = "21.4.0"
google-gms-play-services-ads = "24.5.0"
google-material = "1.12.0"

firebase-crashlytics = "3.0.6"
firebase-perf = "2.0.0"
firebase-bom = "34.1.0"
tensorflow-lite = "2.17.0"

junit5 = "1.13.1.0"
junit = "5.13.4"
junit4 = "4.13.2"
mockk = "1.14.5"

desugar-jdk-libs = "2.1.5"

sonarqube = "6.2.0.5505"

[libraries]

jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
google-identity-googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "google-identity-googleid" }
jetbrains-kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "jetbrains-kotlinx-collections-immutable" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrains-kotlinx-serialization" }
jetbrains-kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "jetbrains-kotlinx-serialization" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "jetbrains-kotlinx-datetime" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-splash = { module = "androidx.core:core-splashscreen", version = "1.2.0-rc01" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-material-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
google-gms-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "google-gms-play-services-location" }
google-gms-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-gms-play-services-auth" }
google-gms-play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "google-gms-play-services-ads" }
google-maps-utils = { module = "com.google.maps.android:android-maps-utils", version = "3.14.0" }
google-maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version = "5.2.0" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-ml-modeldownloader = { module = "com.google.firebase:firebase-ml-modeldownloader" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflow-lite" }

hlcaptain-compose-scrollbar = { module = "com.github.HLCaptain:compose-scrollbar", version.ref = "hlcaptain-compose-scrollbar" }
saket-swipe = { module = "me.saket.swipe:swipe", version.ref = "saket-swipe" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
solarized = { module = "com.github.phototime:solarized-android", version.ref = "solarized" }
apache-commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "apache-commons-math3" }

mapbox-maps = { module = "com.mapbox.maps:android-ndk27", version.ref = "mapbox-maps" }
mapbox-maps-compose = { module = "com.mapbox.extension:maps-compose-ndk27", version.ref = "mapbox-maps" }
mapbox-search = { module = "com.mapbox.search:mapbox-search-android-ui-ndk27", version.ref = "mapbox-search" }
mapbox-navigation = { module = "com.mapbox.navigationcore:android-ndk27", version.ref = "mapbox-navigation" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
placeholder = { module = "com.eygraber:compose-placeholder-material3", version = "1.0.11" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-bottom-sheet = { module = "io.github.raamcosta.compose-destinations:bottom-sheet", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
junit-junit4 = { module = "junit:junit", version.ref = "junit4" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
androidx-room = { id = "androidx.room", version.ref = "room" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation-safeargs" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # From Kotlin 2.0.0-RC2
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "google-secrets" }
google-gms-services = { id = "com.google.gms.google-services", version.ref = "google-gms-services" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]

